//
// Created by Diya Shenoy on 2019-09-29.
//

#ifndef FINANCECALCULATOR_MONTHLY_LOAN_PAYMENT_HPP
#define FINANCECALCULATOR_MONTHLY_LOAN_PAYMENT_HPP

void monthly_payment();

#endif //FINANCECALCULATOR_MONTHLY_LOAN_PAYMENT_HPP
